### PR TITLE
Added the link of the website in readme file

### PR DESCRIPTION
**Pull request by safar1212**
In this pull request, I deployed my portfolio in Github pages and added the link of the website in the readme file.

### CODE REVIEW

**Review by ReshyResh — APPROVED** [review]
# Hi @safar1212 , 

### Your project is complete!  There is nothing else to say other than... it's time to merge it!
#### Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Comment by safar1212** [comment]
> # Hi @safar1212 ,
> ### Your project is complete! There is nothing else to say other than... it's time to merge it!
> #### Congratulations! 🎉
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_



> # Hi @safar1212 ,
> ### Your project is complete! There is nothing else to say other than... it's time to merge it!
> #### Congratulations! 🎉
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_



> # Hi @safar1212 ,
> ### Your project is complete! There is nothing else to say other than... it's time to merge it!
> #### Congratulations! 🎉
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

@ReshyResh 
Thank you for the review. 
Actually, I have a question. Could you please tell me how was the contact form looks on your side? Because, as I have checked the input area with the text area at the bottom of the website looks perfect. But the previous reviewer told me that the length of the text area isn't equal to the length of full name and email input.

Can you please check that at your side, and tell me if everything works fine at your side.
Looking forward!

Thanks in advance!

**Comment by ReshyResh** [comment]
@safar1212 
I've seen this issue, but as this review was only about deployment and you've been approved already, I didn't comment on it. But yeah, the lenghts are different, I'm using a Full HD (1920x1080) screen.

**Comment by safar1212** [comment]
@ReshyResh,
Thank you so much for your response. Actually, when I check it on my laptop. Everything seems perfect. Before, I used a CSS grid for this section. And the length of the name and email input was lower than the text area. Then the reviewer suggested I use flexbox. I used flexbox, and now it's vice versa.
Do you have any idea, why this problem occurs and how to resolve it?

**Comment by ReshyResh** [comment]
The textarea has a fixed width of `299px` while the others div have it dynamic. Remove the hardcoded width from it and make it responsive 👍

**Comment by safar1212** [comment]
Okay! thank you so much for your help

**Pull request merged**
